# A2A Agent Ports
TOPSIDES_AGENT_PORT=9001
FUIMS_AGENT_PORT=9002
PSV_AGENT_PORT=9003
SUBSEA_AGENT_PORT=9004
PIPELINE_AGENT_PORT=9005
CORROSION_AGENT_PORT=9006
METHODS_AGENT_PORT=9007
ORCHESTRATOR_PORT=9010

# Network Configuration
AGENT_HOST=localhost  # Use service names in Docker
A2A_PROTOCOL=jsonrpc

# OpenRouter (existing)
OPENROUTER_API_KEY=sk-or-v1-...
OPENROUTER_MODEL=openai/gpt-4o-mini